config/routes.rb
Rails.application.routes.draw do
  resources :users
  root 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
require 'httparty'
class User < ApplicationRecord


  def self.search(email)
    response = HTTParty.get("http://apilayer.net/api/check?access_key=1a87bda4e25b3152177ec15a5482ac36&email=#{ email }&smtp=1&format=1")
    response["mx_found"]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    @emails = []
    unless(params[:first_name].blank? && params[:last_name].blank? && params[:url].blank?)
      first_name = params[:first_name]
      last_name = params[:last_name]
      url = params[:url]
      @emails = [
      "#{first_name}.#{last_name}@#{params[:url]}",
      "#{first_name}@#{params[:url]}",
      "#{first_name}@#{params[:url]}",
      "#{first_name}.#{last_name}@#{params[:url]}",
      "#{first_name[0.1]}.#{last_name}@#{params[:url]}",
      "#{first_name[0.1]}#{last_name[0.1]}@#{params[:url]}"]
    end
    @emails.each do |email|
      is_found = User.search(email)
      if is_found
        @user = User.create email: email, first_name: first_name, last_name: last_name, url: url
      end
      @user.present? && return
    end
    @user.present? && @users << @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CustomSearch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<div>

<%= form_tag(users_path, method: "get") do %>
  <%= text_field_tag(:first_name, params[:first_name], placeholder: 'FirstName') %>
  <%= text_field_tag(:last_name, params[:last_name], placeholder: 'LastName') %>
  <%= text_field_tag(:url, params[:url], placeholder: 'URL') %>
  <%= submit_tag("Search") %>
<% end %>



</div>
<h1>Users</h1>

<table>
  <thead>
      <h2>Found Users</h2>
  </thead>

  <tbody>
    <th>First Name</th>
    <th>Last Name</th>
    <th>First Name</th>
    <th>URL</th>
    <th>Email</th>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.url %></td>
        <td><%= user.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @user.url %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>